# Generated by Django 4.0.4 on 2022-04-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodule',
            name='pricelist',
        ),
        migrations.AddField(
            model_name='servicemodule',
            name='pricelist',
            field=models.ManyToManyField(related_name='modules', to='estimation.servicepricelist', verbose_name='модуль'),
        ),
    ]
