# Generated by Django 4.0.4 on 2022-04-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0002_remove_servicemodule_pricelist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodule',
            name='pricelist',
        ),
        migrations.AddField(
            model_name='servicemodule',
            name='pricelist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='estimation.servicepricelist', verbose_name='прайс-листы'),
            preserve_default=False,
        ),
    ]
