# Generated by Django 4.0.4 on 2022-04-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0003_remove_servicemodule_pricelist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricelist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estimation.servicepricelist')),
            ],
        ),
    ]
