# Generated by Django 4.0.4 on 2022-04-14 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0004_defaultpricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultpricelist',
            name='default',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='defaultpricelist',
            name='pricelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='is_default', to='estimation.servicepricelist'),
        ),
    ]
