# Generated by Django 4.0.4 on 2022-04-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0005_defaultpricelist_default_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultpricelist',
            old_name='default',
            new_name='status',
        ),
    ]
