# Generated by Django 4.0.4 on 2022-04-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0006_rename_default_defaultpricelist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpricelist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
