# Generated by Django 4.0.4 on 2022-04-14 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0007_alter_defaultpricelist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultpricelist',
            name='status',
        ),
        migrations.AddField(
            model_name='defaultpricelist',
            name='provide_unique',
            field=models.PositiveSmallIntegerField(default=None, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='defaultpricelist',
            name='pricelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_status', to='estimation.servicepricelist'),
        ),
    ]
