# Generated by Django 4.0.4 on 2022-04-14 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0009_remove_defaultpricelist_provide_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepricelist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='defaultpricelist',
            name='pricelist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_status', to='estimation.servicepricelist'),
        ),
    ]
