# Generated by Django 4.0.4 on 2022-05-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0011_alter_defaultpricelist_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='amo_lead_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
