# Generated by Django 3.2.9 on 2022-07-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0012_alter_estimation_amo_lead_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimation',
            options={'ordering': ['-created_at']},
        ),
    ]
