# Generated by Django 3.2.9 on 2021-12-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.IntegerField()),
                ('field_name', models.CharField(default='0', max_length=50)),
                ('field_type', models.CharField(default='str', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.IntegerField(unique=True, verbose_name='id лида')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='материал')),
                ('specialist', models.CharField(blank=True, max_length=50, null=True, verbose_name='мастер')),
                ('contract_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='номер договора')),
                ('contract_start_date', models.IntegerField(verbose_name='дата начала')),
                ('contract_duration', models.FloatField(verbose_name='срок по договору')),
                ('work_duration', models.FloatField(verbose_name='срок изготовления')),
                ('work_start_date', models.IntegerField(verbose_name='дата передачи в работу')),
                ('must_be_ready', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('exipires_in', models.IntegerField()),
                ('access_token', models.CharField(blank=True, max_length=200, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
