# Generated by Django 3.2.9 on 2021-12-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amoApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contract_duration',
            field=models.IntegerField(verbose_name='срок по договору'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='work_duration',
            field=models.IntegerField(verbose_name='срок изготовления'),
        ),
    ]
