# Generated by Django 3.2.9 on 2021-12-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amoApi', '0002_auto_20211224_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contract_duration',
            field=models.IntegerField(null=True, verbose_name='срок по договору'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='work_duration',
            field=models.IntegerField(null=True, verbose_name='срок изготовления'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='work_start_date',
            field=models.IntegerField(null=True, verbose_name='дата передачи в работу'),
        ),
    ]
