# Generated by Django 3.2.9 on 2021-12-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amoApi', '0003_auto_20211224_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='must_be_ready',
            field=models.IntegerField(null=True),
        ),
    ]
