# Generated by Django 3.2.9 on 2021-12-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amoApi', '0005_auto_20211227_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='lead_status',
            new_name='status_id',
        ),
    ]
