# Generated by Django 3.2.9 on 2021-12-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amoApi', '0006_rename_lead_status_lead_status_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='exipires_in',
            new_name='expires_in',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='type',
            new_name='token_type',
        ),
    ]
