# Generated by Django 3.2.9 on 2021-12-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amoApi', '0007_auto_20211227_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contract_duration',
            field=models.IntegerField(default=0, null=True, verbose_name='срок по договору'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='work_duration',
            field=models.IntegerField(default=0, null=True, verbose_name='срок изготовления'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='work_start_date',
            field=models.IntegerField(default=0, null=True, verbose_name='дата передачи в работу'),
        ),
    ]
