# Generated by Django 3.2.9 on 2021-12-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amoApi', '0009_alter_lead_contract_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
