# Generated by Django 3.2.9 on 2021-12-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amoApi', '0010_auto_20211228_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['contract_start_date']},
        ),
    ]
