# Generated by Django 3.2.9 on 2021-12-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='acryliccollection',
            unique_together=set(),
        ),
    ]
