# Generated by Django 3.2.9 on 2021-12-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0002_currency_value_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='acrylicconfiguration',
            unique_together={('alias', 'collection', 'thickness')},
        ),
    ]
