# Generated by Django 3.2.9 on 2021-12-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0002_alter_acryliccollection_unique_together'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='acrylicmanufacturer',
        #     name='additional_info',
        #     field=models.TextField(blank=True, null=True),
        # ),
        migrations.AlterUniqueTogether(
            name='acryliccollection',
            unique_together={('manufacturer', 'name')},
        ),
    ]
