# Generated by Django 3.2.9 on 2021-12-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0003_alter_acrylicconfiguration_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acryliccollection',
            options={'ordering': ['priority', '_standart_price', 'name'], 'verbose_name': 'акриловая коллекция', 'verbose_name_plural': 'акриловые коллекции'},
        ),
        migrations.AlterModelOptions(
            name='acrylicconfiguration',
            options={'ordering': ['-raw_price'], 'verbose_name': 'конфигурация текстуры', 'verbose_name_plural': 'конфигурации текстуры'},
        ),
        migrations.AddField(
            model_name='acryliccollection',
            name='_standart_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
