# Generated by Django 3.2.9 on 2021-12-16 13:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0003_auto_20211213_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrylicstone',
            name='configurations',
            field=models.ManyToManyField(
                related_name='stones', to='stonepricelist.AcrylicConfiguration', verbose_name='конфигурации'),
        ),
    ]
