# Generated by Django 3.2.9 on 2021-12-16 13:46

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0003_auto_20211213_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrylicstone',
            name='configurations',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='collection', chained_model_field='collection_filter', related_name='stones', to='stonepricelist.AcrylicConfiguration', verbose_name='конфигурации'),
        ),
    ]
