# Generated by Django 3.2.9 on 2021-12-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0004_auto_20211210_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acryliccollection',
            options={'ordering': ['priority', '_standart_raw_price', 'name'], 'verbose_name': 'акриловая коллекция', 'verbose_name_plural': 'акриловые коллекции'},
        ),
        migrations.RemoveField(
            model_name='acryliccollection',
            name='_standart_price',
        ),
        migrations.AddField(
            model_name='acryliccollection',
            name='_standart_raw_price',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='стоимость стандартной конфигурации'),
        ),
        migrations.AlterField(
            model_name='acrylicconfiguration',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
