# Generated by Django 3.2.9 on 2021-12-16 13:48

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0004_alter_acrylicstone_configurations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrylicstone',
            name='collection',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='manufacturer', chained_model_field='manufacturer', on_delete=django.db.models.deletion.CASCADE, related_name='stones', to='stonepricelist.acryliccollection', verbose_name='коллекция'),
        ),
        migrations.AlterField(
            model_name='acrylicstone',
            name='configurations',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='collection', chained_model_field='collection_filter', to='stonepricelist.AcrylicConfiguration', verbose_name='конфигурации'),
        ),
    ]
