# Generated by Django 3.2.9 on 2021-12-16 13:48

from django.db import migrations
import django.db.models.deletion
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0004_alter_acrylicstone_configurations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrylicstone',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='stones', to='stonepricelist.acryliccollection', verbose_name='коллекция'),
        ),
        migrations.AlterField(
            model_name='acrylicstone',
            name='configurations',
            field=models.ManyToManyField(
                to='stonepricelist.AcrylicConfiguration', verbose_name='конфигурации'),
        ),
    ]
