# Generated by Django 3.2.9 on 2021-12-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0005_auto_20211216_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='acrylicstone',
            name='notStandart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acrylicstone',
            name='configurations',
            field=models.ManyToManyField(
                null=True, to='stonepricelist.AcrylicConfiguration', verbose_name='конфигурации'),
        ),
    ]
