# Generated by Django 3.2.9 on 2021-12-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0005_auto_20211210_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrylicmanufacturer',
            name='vendor_discount',
            field=models.FloatField(default=0.0, verbose_name='скидка поставщика, %'),
        ),
    ]
