# Generated by Django 3.2.9 on 2021-12-17 10:30

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0006_auto_20211216_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='acrylicstone',
            name='isWhite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acrylicstone',
            name='configurations',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='collection', chained_model_field='collection', null=True, to='stonepricelist.AcrylicConfiguration', verbose_name='конфигурации'),
        ),
    ]
