# Generated by Django 3.2.9 on 2021-12-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0007_auto_20211217_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acrylicstone',
            name='configurations',
        ),
    ]
