# Generated by Django 3.2.9 on 2021-12-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0009_acrylicstone_configuratons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acrylicstone',
            name='configuratons',
        ),
        migrations.RemoveField(
            model_name='acrylicstone',
            name='isWhite',
        ),
        migrations.RemoveField(
            model_name='acrylicstone',
            name='notStandart',
        ),
        migrations.AddField(
            model_name='acryliccollection',
            name='isWhite',
            field=models.BooleanField(default=False),
        ),
    ]
