# Generated by Django 3.2.9 on 2021-12-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0010_auto_20211217_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='additionalWorkAcryl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('measurement', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.CharField(blank=True, max_length=100, null=True)),
                ('spendings', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
