# Generated by Django 3.2.9 on 2021-12-22 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0011_additionalworkacryl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrylicstone',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stones', to='stonepricelist.acrylicmanufacturer', verbose_name='производитель'),
        ),
    ]
