# Generated by Django 3.2.9 on 2021-12-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0004_merge_0003_auto_20211213_2053_0003_auto_20211213_2107'),
        ('stonepricelist', '0011_additionalworkacryl'),
    ]

    operations = [
    ]
