# Generated by Django 3.2.9 on 2021-12-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0012_alter_acrylicstone_manufacturer'),
        ('stonepricelist', '0012_merge_20211217_1824'),
    ]

    operations = [
    ]
