# Generated by Django 3.2.9 on 2022-01-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0012_alter_acrylicstone_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acrylicstone',
            name='similar_textures',
        ),
        migrations.AddField(
            model_name='acrylicstone',
            name='equivalents',
            field=models.ManyToManyField(blank=True, related_name='_stonepricelist_acrylicstone_equivalents_+', to='stonepricelist.AcrylicStone', verbose_name='похожие текстуры'),
        ),
    ]
