# Generated by Django 3.2.9 on 2022-01-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0013_merge_20211222_1330'),
        ('stonepricelist', '0016_auto_20220114_1339'),
    ]

    operations = [
    ]
