# Generated by Django 3.2.9 on 2022-01-17 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0016_auto_20220114_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='additionalworkacryl',
            options={'verbose_name': 'дополнительная работа', 'verbose_name_plural': 'дополнительные работы'},
        ),
        migrations.RemoveField(
            model_name='acrylicstone',
            name='equivalents',
        ),
        migrations.AddField(
            model_name='acrylicstone',
            name='equivalents_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stonepricelist.equivalentgroup'),
        ),
    ]
