# Generated by Django 3.2.9 on 2022-01-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0017_auto_20220117_1545'),
        ('stonepricelist', '0017_merge_20220114_1406'),
    ]

    operations = [
    ]
