# Generated by Django 3.2.9 on 2022-01-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0017_auto_20220117_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equivalentgroup',
            options={'verbose_name': 'группа аналогов', 'verbose_name_plural': 'группы аналогов'},
        ),
        migrations.AddField(
            model_name='acryliccollection',
            name='main_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, null=True, verbose_name='цвет карточки'),
        ),
        migrations.AlterField(
            model_name='acrylicstone',
            name='equivalents_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stones', to='stonepricelist.equivalentgroup'),
        ),
    ]
