# Generated by Django 3.2.9 on 2022-01-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0018_auto_20220118_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acryliccollection',
            name='main_color',
        ),
    ]
