# Generated by Django 3.2.9 on 2022-01-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0019_remove_acryliccollection_main_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='acrylicmanufacturer',
            name='card_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
