# Generated by Django 3.2.9 on 2022-01-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0020_acrylicmanufacturer_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrylicmanufacturer',
            name='card_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='цвет карточки'),
        ),
    ]
