# Generated by Django 3.2.9 on 2022-01-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0018_merge_20220117_1910'),
        ('stonepricelist', '0021_alter_acrylicmanufacturer_card_color'),
    ]

    operations = [
    ]
