# Generated by Django 3.2.9 on 2022-03-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0022_merge_20220118_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='acrylicmanufacturer',
            name='currency_value_override',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ручной курс валют'),
        ),
    ]
