# Generated by Django 3.2.9 on 2022-03-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0026_auto_20220302_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='acrylicstone',
            name='texture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stonepricelist.texture', verbose_name='текстура'),
        ),
        migrations.AddField(
            model_name='quartzstone',
            name='texture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stonepricelist.texture', verbose_name='текстура'),
        ),
    ]
