# Generated by Django 3.2.9 on 2022-03-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0027_auto_20220302_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartzmanufacturer',
            name='surface_configurations',
            field=models.ManyToManyField(to='stonepricelist.SurfaceType', verbose_name='список полировок'),
        ),
        migrations.AddField(
            model_name='quartzmanufacturer',
            name='thickness_configurations',
            field=models.ManyToManyField(to='stonepricelist.Texture', verbose_name='варианты толщин'),
        ),
    ]
