# Generated by Django 3.2.9 on 2022-03-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0028_auto_20220302_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartzmanufacturer',
            name='thickness_configurations',
            field=models.ManyToManyField(to='stonepricelist.Thickness', verbose_name='варианты толщин'),
        ),
    ]
