# Generated by Django 3.2.9 on 2022-03-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0029_alter_quartzmanufacturer_thickness_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartzmanufacturer',
            name='size_configurations',
            field=models.ManyToManyField(to='stonepricelist.SlabSize', verbose_name='списк размеров'),
        ),
    ]
