# Generated by Django 3.2.9 on 2022-03-02 14:43

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0031_auto_20220302_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartzstoneconfiguration',
            name='thickness',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='stone', chained_model_field='thickness_configurations', on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='stonepricelist.thickness', verbose_name='толщина камня'),
        ),
    ]
