# Generated by Django 3.2.9 on 2022-03-02 14:43

from django.db import migrations
import django.db.models.deletion
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0031_auto_20220302_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartzstoneconfiguration',
            name='thickness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations',
                                    to='stonepricelist.thickness', verbose_name='толщина камня'),
        ),
    ]
