# Generated by Django 3.2.9 on 2022-03-02 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0033_alter_quartzstoneconfiguration_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartzstoneconfiguration',
            name='thickness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='stonepricelist.thickness', verbose_name='толщина камня'),
        ),
    ]
