# Generated by Django 3.2.9 on 2022-03-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0035_rename_size_configurations_quartzmanufacturer_slab_size_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartzstoneconfiguration',
            name='is_on_order',
            field=models.BooleanField(default=False),
        ),
    ]
