# Generated by Django 3.2.9 on 2022-03-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0037_alter_quartzstoneconfiguration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='acrylicmanufacturer',
            name='currency_multiplier_percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='дополнительная наценка на курс'),
        ),
        migrations.AddField(
            model_name='quartzmanufacturer',
            name='currency_multiplier_percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='дополнительная наценка на курс'),
        ),
    ]
