# Generated by Django 3.2.9 on 2022-03-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0040_rename_updated_at_quartzstone_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slabsize',
            options={'ordering': ['priority'], 'verbose_name': 'размер слэба', 'verbose_name_plural': 'размеры слэбов'},
        ),
        migrations.AlterModelOptions(
            name='surfacetype',
            options={'ordering': ['priority'], 'verbose_name': 'тип поверхности', 'verbose_name_plural': 'типы поверхностей'},
        ),
        migrations.AlterModelOptions(
            name='thickness',
            options={'ordering': ['priority'], 'verbose_name': 'толщина камня', 'verbose_name_plural': 'толщины камней'},
        ),
        migrations.AddField(
            model_name='slabsize',
            name='priority',
            field=models.SmallIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='surfacetype',
            name='priority',
            field=models.SmallIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='thickness',
            name='priority',
            field=models.SmallIntegerField(default=500),
        ),
    ]
