# Generated by Django 3.2.9 on 2022-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0041_auto_20220305_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='acrylicmanufacturer',
            name='currency_value_modified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quartzmanufacturer',
            name='currency_value_modified_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
