# Generated by Django 3.2.9 on 2022-03-18 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0042_auto_20220317_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='quartzManufacturerInfoPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stonepricelist.quartzmanufacturer')),
            ],
        ),
    ]
