# Generated by Django 3.2.9 on 2022-03-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0043_quartzmanufacturerinfopictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartzmanufacturerinfopictures',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='quartzmanufacturerinfopictures',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_images', to='stonepricelist.quartzmanufacturer'),
        ),
    ]
