# Generated by Django 3.2.9 on 2022-03-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0046_alter_quartzmanufacturerinfopictures_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(blank=True, default='USD', max_length=3, null=True, unique=True, verbose_name='код валюты ЦБ'),
        ),
    ]
