# Generated by Django 3.2.9 on 2022-03-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0047_auto_20220324_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuartzSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.JSONField(blank=True, null=True)),
                ('manufacturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='stonepricelist.quartzmanufacturer')),
            ],
        ),
    ]
