# Generated by Django 3.2.9 on 2022-03-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0048_quartzschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartzschema',
            name='advanced_surface_display',
            field=models.BooleanField(default=False),
        ),
    ]
