# Generated by Django 3.2.9 on 2022-04-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0050_quartzstoneconfiguration_overprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='acrylicstone',
            name='info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='quartzstone',
            name='info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
