# Generated by Django 3.2.9 on 2022-04-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0051_auto_20220404_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartzstoneconfiguration',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='артикул'),
        ),
    ]
