# Generated by Django 3.2.9 on 2022-04-05 14:52

from django.db import migrations, models
import stonepricelist.quartz_models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0052_quartzstoneconfiguration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartzmanufacturerinfopictures',
            name='image',
            field=models.ImageField(upload_to=stonepricelist.quartz_models.upload_to),
        ),
        migrations.DeleteModel(
            name='QuartzSchema',
        ),
    ]
