# Generated by Django 4.0.4 on 2022-04-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0053_auto_20220405_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrylicstone',
            name='similar_textures',
            field=models.ManyToManyField(blank=True, to='stonepricelist.acrylicstone', verbose_name='похожие текстуры'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='similar_textures',
            field=models.ManyToManyField(blank=True, to='stonepricelist.quartzstone', verbose_name='похожие текстуры'),
        ),
        migrations.AlterField(
            model_name='surfacetype',
            name='similar',
            field=models.ManyToManyField(blank=True, to='stonepricelist.surfacetype', verbose_name='аналогичные'),
        ),
    ]
