# Generated by Django 4.0.4 on 2022-04-12 08:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0054_alter_acrylicstone_similar_textures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartzstone',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='quartzstone',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_column'], name='stonepricel_vector__fc4890_gin'),
        ),
    ]
