# Generated by Django 4.0.4 on 2022-04-29 17:50

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0059_re_trigger2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartzstone',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, max_length=20, null=True),
        ),
    ]
