# Generated by Django 4.0.4 on 2022-05-17 14:28

from decimal import Decimal
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0060_alter_quartzstone_vector_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acrylicmanufacturer',
            name='code',
        ),
        migrations.RemoveField(
            model_name='acrylicmanufacturer',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='acrylicmanufacturer',
            name='currency_multiplier_percent',
        ),
        migrations.RemoveField(
            model_name='acrylicmanufacturer',
            name='currency_value_modified_at',
        ),
        migrations.RemoveField(
            model_name='acrylicmanufacturer',
            name='currency_value_override',
        ),
        migrations.RemoveField(
            model_name='quartzmanufacturer',
            name='code',
        ),
        migrations.RemoveField(
            model_name='quartzmanufacturer',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='quartzmanufacturer',
            name='currency_multiplier_percent',
        ),
        migrations.RemoveField(
            model_name='quartzmanufacturer',
            name='currency_value_modified_at',
        ),
        migrations.RemoveField(
            model_name='quartzmanufacturer',
            name='currency_value_override',
        ),
        migrations.AlterField(
            model_name='acrylicmanufacturer',
            name='vendor_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='скидка поставщика, %'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='material',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='наценка, %'),
        ),
        migrations.AlterField(
            model_name='quartzmanufacturer',
            name='vendor_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='скидка поставщика, %'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CurrencyModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='наценка, %')),
                ('floor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='минимальное значение')),
                ('ceiling', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='максимальное значение значение')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='stonepricelist.currency')),
            ],
        ),
    ]
