# Generated by Django 4.0.4 on 2022-05-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0061_remove_acrylicmanufacturer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acrylicmanufacturer',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stonepricelist.currencymodifier', verbose_name='валюта распространения'),
        ),
        migrations.AddField(
            model_name='quartzmanufacturer',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stonepricelist.currencymodifier', verbose_name='валюта распространения'),
        ),
    ]
