# Generated by Django 3.2.9 on 2022-07-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonepricelist', '0062_acrylicmanufacturer_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrylicstone',
            name='similar_textures',
            field=models.ManyToManyField(blank=True, related_name='_stonepricelist_acrylicstone_similar_textures_+', to='stonepricelist.AcrylicStone', verbose_name='похожие текстуры'),
        ),
        migrations.AlterField(
            model_name='currencymodifier',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='stonepricelist.currency', verbose_name='валюта основы'),
        ),
        migrations.AlterField(
            model_name='currencymodifier',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название схемы'),
        ),
        migrations.AlterField(
            model_name='quartzstone',
            name='similar_textures',
            field=models.ManyToManyField(blank=True, related_name='_stonepricelist_quartzstone_similar_textures_+', to='stonepricelist.QuartzStone', verbose_name='похожие текстуры'),
        ),
        migrations.AlterField(
            model_name='surfacetype',
            name='similar',
            field=models.ManyToManyField(blank=True, related_name='_stonepricelist_surfacetype_similar_+', to='stonepricelist.SurfaceType', verbose_name='аналогичные'),
        ),
    ]
