// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConstField: typeof import('./src/components/ConstField.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    FormulaBlock: typeof import('./src/components/FormulaBlock.vue')['default']
    ModuleEdit: typeof import('./src/components/ModuleEdit.vue')['default']
    ModuleSettings: typeof import('./src/components/ModuleSettings.vue')['default']
    PriceListConstantsBlock: typeof import('./src/components/PriceListConstantsBlock.vue')['default']
    PriceListHome: typeof import('./src/components/PriceListHome.vue')['default']
    PriceListNew: typeof import('./src/components/PriceListNew.vue')['default']
    Radio: typeof import('./src/components/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectorFields: typeof import('./src/components/SelectorFields.vue')['default']
    TemplatesBlock: typeof import('./src/components/TemplatesBlock.vue')['default']
    TemplateSelector: typeof import('./src/components/TemplateSelector.vue')['default']
    Variable: typeof import('./src/components/Variable.vue')['default']
  }
}

export {}
