# Generated by Django 3.2.9 on 2021-12-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='pricelist_id',
            field=models.IntegerField(default=1),
        ),
    ]
