# Generated by Django 3.2.9 on 2022-01-24 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_calculation_pricelist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_creations', to=settings.AUTH_USER_MODEL),
        ),
    ]
