# Generated by Django 3.2.9 on 2022-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_calculation_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
