# Generated by Django 3.2.9 on 2022-01-24 11:43

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_pricelist_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='values',
            field=models.JSONField(default=main.models.defaultCalculationData),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
