# Generated by Django 3.2.9 on 2022-01-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220124_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationtemplate',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
