# Generated by Django 3.2.9 on 2022-02-04 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_calculation_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('state_before', models.JSONField(default=main.models.defaultCalculationData)),
                ('mutation', models.JSONField(blank=True, null=True)),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='main.calculation')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mutations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
