# Generated by Django 3.2.9 on 2022-01-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_graph', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecialistCount',
            new_name='SpecialistsCount',
        ),
    ]
