// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Acryl: typeof import('./src/components/pricelist/Acryl.vue')['default']
    Controls: typeof import('./src/components/settings/Controls.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDatetimepicker: typeof import('element-plus/es')['ElDatetimepicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    General: typeof import('./src/components/settings/General.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Import: typeof import('./src/components/settings/Import.vue')['default']
    ImportSession: typeof import('./src/components/settings/ImportSession.vue')['default']
    Main: typeof import('./src/components/settings/Main.vue')['default']
    Material: typeof import('./src/components/pricelist/Material.vue')['default']
    Prices: typeof import('./src/components/pricelist/Prices.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/pricelist/Sidebar.vue')['default']
  }
}
