// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Constant: typeof import('./src/components/Constant.vue')['default']
    ConstantButtons: typeof import('./src/components/ConstantButtons.vue')['default']
    ConstantFields: typeof import('./src/components/ConstantFields.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Estimation: typeof import('./src/components/Estimation.vue')['default']
    FieldSelector: typeof import('./src/components/FieldSelector.vue')['default']
    FieldVariable: typeof import('./src/components/FieldVariable.vue')['default']
    Logistics: typeof import('./src/components/Logistics.vue')['default']
    Materials: typeof import('./src/components/Materials.vue')['default']
    ModuleFields: typeof import('./src/components/ModuleFields.vue')['default']
    Product: typeof import('./src/components/Product.vue')['default']
    ProductEdit: typeof import('./src/components/ProductEdit.vue')['default']
    Results: typeof import('./src/components/Results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoneInfoCard: typeof import('./src/components/StoneInfoCard.vue')['default']
    StoneSelector: typeof import('./src/components/StoneSelector.vue')['default']
  }
}

export {}
