# Generated by Django 3.2.9 on 2022-07-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone_pricelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='addons',
            field=models.ManyToManyField(null=True, related_query_name='addons', to='stone_pricelist.MaterialAddon', verbose_name='дополнительные поля'),
        ),
    ]
