# Generated by Django 3.2.9 on 2022-07-04 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stone_pricelist', '0003_alter_material_addons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='cut_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='stone_pricelist.currencymodifier', verbose_name='валюта распила'),
        ),
    ]
