# Generated by Django 3.2.9 on 2022-07-04 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stone_pricelist', '0004_alter_manufacturer_cut_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['priority'], 'verbose_name': 'производитель', 'verbose_name_plural': 'производители'},
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturers', to='stone_pricelist.currencymodifier', verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stone_pricelist.material', verbose_name='материал'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stones', to='stone_pricelist.collection', verbose_name='коллекция'),
        ),
    ]
