# Generated by Django 3.2.9 on 2022-07-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone_pricelist', '0006_alter_stone_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='bitrix_id',
            field=models.TextField(blank=True, null=True, verbose_name='id битрикс'),
        ),
    ]
