# Generated by Django 3.2.9 on 2022-07-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone_pricelist', '0007_alter_stone_bitrix_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
