# Generated by Django 3.2.9 on 2022-07-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone_pricelist', '0008_alter_pricelist_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='margindiscount',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
    ]
