# Generated by Django 3.2.9 on 2022-07-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone_pricelist', '0009_margindiscount_is_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoneconfiguration',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
