# Generated by Django 3.2.9 on 2022-07-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone_pricelist', '0010_stoneconfiguration_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='alias',
            field=models.CharField(default=3, max_length=25, unique=True, verbose_name='кодовое название'),
            preserve_default=False,
        ),
    ]
